import type { Question } from "./types";

export const QUESTIONS_EN: Question[] = [
  {
    id: "speed",
    eyebrow: "01 · Speed",
    prompt: "How fast does your website load?",
    helper: "If you haven't measured it, pick the feeling closest to your experience today.",
    whyItMatters:
      "Speed conditions attention even before the user reads your message. If the first screen takes too long, the friction has already started.",
    tip: "Think about real mobile conditions—mobile data, not just desktop Wi-Fi.",
    options: [
      {
        id: "under-2",
        label: "Under 2 seconds",
        detail: "Feels fast and responds almost instantly.",
        score: 95,
        areaLabel: "Solid speed",
        recommendation: "Keep images, scripts and above-the-fold weight under control.",
        target: "Current goal met",
      },
      {
        id: "between-2-4",
        label: "Between 2 and 4 seconds",
        detail: "Still usable, but it already adds friction on mobile.",
        score: 62,
        areaLabel: "Speed with friction",
        recommendation: "Reduce visual weight, review images and eliminate unnecessary above-the-fold scripts.",
        target: "Get under 2 seconds",
      },
      {
        id: "over-4",
        label: "Over 4 seconds",
        detail: "You're probably losing attention before the main message.",
        score: 24,
        areaLabel: "Critical speed",
        recommendation: "Prioritize performance before adding more design: asset optimization, layout and initial load.",
        target: "Cut more than 50% of load time",
      },
    ],
  },
  {
    id: "clarity",
    eyebrow: "02 · Clarity",
    prompt: "Is it clear what the visitor should do?",
    helper: "We're looking for one obvious primary action — not multiple options competing with each other.",
    whyItMatters:
      "A website can look good and still fail if it doesn't guide. When the primary action isn't obvious, attention scatters and conversion drops.",
    tip: "If your visitor doesn't understand what to do in 5 seconds, there's a clear improvement opportunity.",
    options: [
      {
        id: "very-clear",
        label: "Yes, very clear",
        detail: "The primary action is defined and visible.",
        score: 92,
        areaLabel: "Clear message",
        recommendation: "Refine copy and visual hierarchy to sustain that clarity on both mobile and desktop.",
        target: "Keep one dominant CTA",
      },
      {
        id: "somewhat-clear",
        label: "Sort of",
        detail: "There's intent, but it's diluted by too many things at once.",
        score: 56,
        areaLabel: "Ambiguous message",
        recommendation: "Simplify the headline, reduce distractions and leave one primary action per screen.",
        target: "Visitor understands what to do in 5 seconds",
      },
      {
        id: "not-clear",
        label: "Not really",
        detail: "Right now the website probably informs, but doesn't guide.",
        score: 20,
        areaLabel: "Weak message",
        recommendation: "Define the proposition, primary CTA and reading order before designing more sections.",
        target: "One central message and a single action priority",
      },
    ],
  },
  {
    id: "goal",
    eyebrow: "03 · Goal",
    prompt: "Does your website have a clear objective?",
    helper: "Capturing leads is not the same as selling or informing.",
    whyItMatters:
      "Without a clear primary objective, the structure loses direction. The problem then isn't just design — it's about decisions.",
    tip: "Choosing one priority helps organize content, CTAs, metrics and the user journey.",
    options: [
      {
        id: "leads",
        label: "Generate leads",
        detail: "You want inquiries, meetings or qualified contacts.",
        score: 90,
        areaLabel: "Defined commercial goal",
        recommendation: "Align forms, CTAs and social proof to increase contact intent.",
        target: "Measure visits → inquiries",
      },
      {
        id: "sales",
        label: "Sell",
        detail: "The website has to push toward purchase or booking.",
        score: 86,
        areaLabel: "Defined transactional goal",
        recommendation: "Work on trust, load times and reducing steps before checkout or booking.",
        target: "Measure visits → sales",
      },
      {
        id: "inform",
        label: "Inform",
        detail: "You want to educate or present, but without a strong primary conversion.",
        score: 68,
        areaLabel: "Informational goal",
        recommendation: "Define a useful secondary conversion: contact, demo, download or consultation.",
        target: "Add one measurable secondary action",
      },
      {
        id: "unclear-goal",
        label: "I'm not sure",
        detail: "That usually shows up immediately in the website structure.",
        score: 22,
        areaLabel: "Undefined goal",
        recommendation: "Define first what the website exists for. Without that, design and development lose direction.",
        target: "Choose one primary goal before redesigning",
      },
    ],
  },
];
